FROM python:3.13-slim
WORKDIR /app
RUN pip install kafka-python pandas pyarrow
COPY scripts/kafka_data_simulator.py .
ENV IRION_DATA_DIR=/app/data/bronze
ENV PYTHONUNBUFFERED=1
CMD ["python3", "kafka_data_simulator.py", "--kafka-broker", "kafka:9094"]
